import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import { Home } from "./admin/page";
import "../app/Styles/global.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import AuthGuard from "./components/AuthGuard";

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={`${montserrat.className}`}>
        <AuthGuard>
          {children}
        </AuthGuard>
      </body>
    </html>
  );
}
